### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by braska** [moxystudio/webpack-isomorphic-compiler-reporter#16]
After updating to Webpack 4 I've got following warning:
```
WARN: Server `devtool` in webpack config should be set to `source-map` or `inline-source-map`
```

But Webpack 4 have a lot of defaults. And there is no need to set `devtool` manually (`mode` config variable can be used to control defaults).

**Comment by satazor** [comment]
We are in the process of updating all of our packages to be compatible with Webpack v4. Stay tuned.

**Comment by satazor** [comment]
@braska The newest version no longer verifies`devtool`. I will leave this issue open until we fully support Webpack 4.

**Comment by braska** [comment]
You are incredible! Thanks for the fast reaction. A convenient opportunity to say that you are doing an insanely important project. I am talking about `webpack-isomorphic-dev-middleware` and many others tools around it. Thanks a lot.

**Comment by satazor** [comment]
Thanks for your kind words @braska. This wouldn't be possible without many contributions from our team!

We will be developing and open-sourcing an exciting project that will leverage all this tooling into a CLI and runtime. The goal is to provide a good low-level foundation where different "plugins" can be installed to solve specific problems.

Have you ever thought why nextjs is so popular? I would say that it's because of the following reasons:

- Easy to start up an isomorphic project
- Abstracts all the complexity of using webpack, babel, etc
- Has a built-in router based on file-system
- Solves the data-fetching isomorphically (universally)

Though, when one really wants some flexibility, we usually hit huge walls. Additionally some of their assumptions are opinionated and doesn't fit everyone. Now imagine a project where you would install different packages that integrate into this tool to solve all the previous items individually? You can even create a preset where you "activate" these packages (similar to a babel preset) and use it among similar projects or companies.

That's what we will be building in the next couple of months. It resembles [neutrino](https://github.com/mozilla-neutrino/neutrino-dev) or [razzle](https://github.com/jaredpalmer/razzle) but will use `webpack-isomorphic-dev-middleware` (& friends) and will be much better, hopefully!

**Comment by satazor** [comment]
The latest release already supports v4.

`webpack-isomorphic-dev-middleware` will have support for v4 soon too, subscribe to https://github.com/moxystudio/webpack-isomorphic-dev-middleware/pull/54
