### ISSUE TITLE
Warn of human errors before any compilation event

### ISSUE THREAD

**Issue by andrefgneves** [moxystudio/webpack-isomorphic-compiler-reporter#6]
Should we report human errors before the compilation events start, like I proposed in #5?
If so, and for consistency, we should also update [webpack-isomorphic-dev-middleware](https://github.com/moxystudio/webpack-isomorphic-dev-middleware) to do the same.

**Comment by satazor** [comment]
`webpack-isomorphic-dev-middleware` may only check for human errors after a compilation because it checks the assets which are only available after compiling.

Should we change [this](https://github.com/moxystudio/webpack-isomorphic-compiler-reporter/blob/master/index.js#L32) to end instead? If we do that, we must also do the same for the `error` event and remove both listeners when the check is done.

I don't know if it's necessary to make things complex for such minimal benefit.

**Comment by andrefgneves** [comment]
Yes, I agree it's not worth it. Closing.
